### ISSUE TITLE
I see this issue, Any solution? or what possibly I am doing wrong?

### ISSUE THREAD

**Issue by imtrinity94** [Aveek-Saha/spotify-box#5]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/7029361/153571347-27eb6863-5ee7-4ebd-aa70-1a2a26ad1ec3.png">

**Comment by Aveek-Saha** [comment]
Have you created the environment variables for CLIENT_ID, CLIENT_SECRET and REFRESH_TOKEN?
